import LandingpageModule from "@/components/modules/LandingpageModule";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Giới thiệu về StuSp",
  description: "Generated by create next app",
  icons: "/StuSp.svg",
};

export default function LandingPage() {
  return <LandingpageModule />;
}
