import SettingAccountPage from "@/components/modules/SettingModule/SettingAccountPage";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "StuSp - latest",
  description: "Generated by create next app",
  icons: "/StuSp.svg",
};

export default function EditPage() {
  return <SettingAccountPage></SettingAccountPage>;
}
