import type { Metadata } from "next";

import ExamAreaModule from "@/components/modules/ExamAreaModule";

export const metadata: Metadata = {
  title: "StuSp - latest",
  description: "Generated by create next app",
  icons: "/StuSp.svg",
};

export default function StudyAreaPage() {
  return <ExamAreaModule></ExamAreaModule>;
}
